/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const FRAME_WIDTH = 192;
const FRAME_HEIGHT = 208;
const FRAME_COUNT = 9;

async function assembleAtlas(charName: string) {
  const runDir = path.join('./char_runs', charName);
  const manifestPath = path.join(runDir, 'manifest.json');

  if (!fs.existsSync(manifestPath)) {
    console.error(`Manifest not found at: ${manifestPath}`);
    process.exit(1);
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
  const rowOrder: string[] = Object.keys(manifest.rows);

  if (manifest.reference?.status !== 'completed') {
    console.warn('Warning: reference image not processed. Visual consistency may be affected.');
  }

  const incomplete = rowOrder.filter(r => manifest.rows[r]?.status !== 'completed');
  if (incomplete.length > 0) {
    console.warn(`Warning: ${incomplete.length} row(s) not completed: ${incomplete.join(', ')}`);
  }

  const atlasWidth = FRAME_COUNT * FRAME_WIDTH;
  const atlasHeight = rowOrder.length * FRAME_HEIGHT;
  const composites: sharp.OverlayOptions[] = [];

  for (let r = 0; r < rowOrder.length; r++) {
    const rowName = rowOrder[r];
    const rowDir = path.join(runDir, 'rows', rowName);
    if (fs.existsSync(rowDir)) {
      for (let c = 0; c < FRAME_COUNT; c++) {
        const framePath = path.join(rowDir, `frame_${c}.png`);
        if (fs.existsSync(framePath)) {
          composites.push({ input: framePath, left: c * FRAME_WIDTH, top: r * FRAME_HEIGHT });
        }
      }
    }
  }

  const outputWebp = path.join(runDir, 'output', 'spritesheet.webp');
  const outputJson = path.join(runDir, 'output', 'char.json');

  await sharp({
    create: { width: atlasWidth, height: atlasHeight, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } }
  })
    .composite(composites)
    .webp({ quality: 90 })
    .toFile(outputWebp);

  const animations = Object.fromEntries(
    rowOrder.map((name, idx) => {
      const row = manifest.rows[name];
      return [name, { row: idx, frameCount: FRAME_COUNT, fps: row.fps ?? 8, loop: row.loop ?? true }];
    })
  );

  const charMetadata = {
    name: charName,
    type: 'char-sprite-v1',
    dimensions: { width: atlasWidth, height: atlasHeight },
    frameSize: { width: FRAME_WIDTH, height: FRAME_HEIGHT },
    rows: rowOrder,
    animations
  };

  fs.writeFileSync(outputJson, JSON.stringify(charMetadata, null, 2));

  updateRegistry(charName, charMetadata);

  console.log(`Atlas assembled: ${outputWebp}`);
  console.log(`Metadata saved: ${outputJson}`);
}

function updateRegistry(charName: string, charMetadata: object) {
  const registryPath = './char_runs/registry.js';
  let registry: Record<string, object> = {};

  if (fs.existsSync(registryPath)) {
    try {
      const src = fs.readFileSync(registryPath, 'utf-8');
      const match = src.match(/window\.CHAR_REGISTRY\s*=\s*(\{[\s\S]*\})\s*;/);
      if (match) registry = JSON.parse(match[1]);
    } catch { /* start fresh */ }
  }

  registry[charName] = { ...charMetadata, spritesheet: `${charName}/output/spritesheet.webp` };

  fs.writeFileSync(
    registryPath,
    `// Auto-generated by assemble.ts — do not edit manually\n` +
    `window.CHAR_REGISTRY = ${JSON.stringify(registry, null, 2)};\n`
  );

  console.log(`Registry updated: ${registryPath}`);
}

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error('Usage: npx tsx skills/char-sprite/assemble.ts <CharName>');
  process.exit(1);
}

assembleAtlas(args[0]).catch(console.error);
