// Auto-generated by assemble.ts — do not edit manually
window.PET_REGISTRY = {
  "Puppy_Grid": {
    "name": "Puppy_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Puppy_Grid/output/spritesheet.webp"
  },
  "Kitten_Grid": {
    "name": "Kitten_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Kitten_Grid/output/spritesheet.webp"
  },
  "Penguin_Grid": {
    "name": "Penguin_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Penguin_Grid/output/spritesheet.webp"
  },
  "Pterosaur_Grid": {
    "name": "Pterosaur_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Pterosaur_Grid/output/spritesheet.webp"
  },
  "Lion_Grid": {
    "name": "Lion_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Lion_Grid/output/spritesheet.webp"
  },
  "Tiger_Grid": {
    "name": "Tiger_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Tiger_Grid/output/spritesheet.webp"
  },
  "Fox_Grid": {
    "name": "Fox_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Fox_Grid/output/spritesheet.webp"
  },
  "Cheetah_Grid": {
    "name": "Cheetah_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Cheetah_Grid/output/spritesheet.webp"
  },
  "Stickman_Grid": {
    "name": "Stickman_Grid",
    "type": "hatch-pet-v1",
    "dimensions": {
      "width": 1728,
      "height": 1248
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "hatching",
      "jumping",
      "running-left",
      "attacking",
      "swift-to-people",
      "sleeping"
    ],
    "animations": {
      "hatching": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "jumping": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "running-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attacking": {
        "row": 3,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      },
      "swift-to-people": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "sleeping": {
        "row": 5,
        "frameCount": 9,
        "fps": 6,
        "loop": true
      }
    },
    "spritesheet": "Stickman_Grid/output/spritesheet.webp"
  }
};
