// Auto-generated by assemble.ts — do not edit manually
window.CHAR_REGISTRY = {
  "MermaidPrincess": {
    "name": "MermaidPrincess",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      }
    },
    "spritesheet": "MermaidPrincess/output/spritesheet.webp"
  },
  "OctopusMonster": {
    "name": "OctopusMonster",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "OctopusMonster/output/spritesheet.webp"
  },
  "Shark": {
    "name": "Shark",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Shark/output/spritesheet.webp"
  },
  "Farmer": {
    "name": "Farmer",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 1040
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "walk-down",
      "walk-up",
      "walk-left",
      "tool-use",
      "sleeping"
    ],
    "animations": {
      "walk-down": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-up": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "tool-use": {
        "row": 3,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "sleeping": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Farmer/output/spritesheet.webp"
  },
  "CatNinja": {
    "name": "CatNinja",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 12,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      }
    },
    "spritesheet": "CatNinja/output/spritesheet.webp"
  },
  "SamuraiBot": {
    "name": "SamuraiBot",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "SamuraiBot/output/spritesheet.webp"
  },
  "Botty": {
    "name": "Botty",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "walk-down",
      "walk-up",
      "walk-left"
    ],
    "animations": {
      "walk-down": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-up": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Botty/output/spritesheet.webp"
  },
  "ShadowBoy": {
    "name": "ShadowBoy",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "run",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "run": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "ShadowBoy/output/spritesheet.webp"
  }
};
