// Auto-generated by assemble.ts — do not edit manually
window.CHAR_REGISTRY = {
  "MermaidPrincess": {
    "name": "MermaidPrincess",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      }
    },
    "spritesheet": "MermaidPrincess/output/spritesheet.webp"
  },
  "OctopusMonster": {
    "name": "OctopusMonster",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "OctopusMonster/output/spritesheet.webp"
  },
  "Shark": {
    "name": "Shark",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Shark/output/spritesheet.webp"
  },
  "Farmer": {
    "name": "Farmer",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 1040
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "walk-down",
      "walk-up",
      "walk-left",
      "tool-use",
      "sleeping"
    ],
    "animations": {
      "walk-down": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-up": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "tool-use": {
        "row": 3,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "sleeping": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Farmer/output/spritesheet.webp"
  },
  "CatNinja": {
    "name": "CatNinja",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 12,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": false
      }
    },
    "spritesheet": "CatNinja/output/spritesheet.webp"
  },
  "SamuraiBot": {
    "name": "SamuraiBot",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk-left"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "SamuraiBot/output/spritesheet.webp"
  },
  "Botty": {
    "name": "Botty",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "walk-down",
      "walk-up",
      "walk-left"
    ],
    "animations": {
      "walk-down": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-up": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Botty/output/spritesheet.webp"
  },
  "ShadowBoy": {
    "name": "ShadowBoy",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "run",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "run": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "ShadowBoy/output/spritesheet.webp"
  },
  "DustCowboy": {
    "name": "DustCowboy",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk",
      "shoot"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "walk": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "shoot": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "DustCowboy/output/spritesheet.webp"
  },
  "DustSheriff": {
    "name": "DustSheriff",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "walk": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "DustSheriff/output/spritesheet.webp"
  },
  "NinjaShade": {
    "name": "NinjaShade",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "run",
      "crouch"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "run": {
        "row": 1,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      },
      "crouch": {
        "row": 2,
        "frameCount": 9,
        "fps": 10,
        "loop": true
      }
    },
    "spritesheet": "NinjaShade/output/spritesheet.webp"
  },
  "SSGirl": {
    "name": "SSGirl",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 832
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "run",
      "jump",
      "hurt"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "run": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "hurt": {
        "row": 3,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "SSGirl/output/spritesheet.webp"
  },
  "SSCat": {
    "name": "SSCat",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "run",
      "jump"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "run": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "jump": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "SSCat/output/spritesheet.webp"
  },
  "SSFish": {
    "name": "SSFish",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "swim",
      "idle"
    ],
    "animations": {
      "swim": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "idle": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "SSFish/output/spritesheet.webp"
  },
  "SSEagle": {
    "name": "SSEagle",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 416
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "fly",
      "glide"
    ],
    "animations": {
      "fly": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "glide": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "SSEagle/output/spritesheet.webp"
  },
  "SSBear": {
    "name": "SSBear",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 624
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "idle",
      "walk",
      "attack"
    ],
    "animations": {
      "idle": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "attack": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "SSBear/output/spritesheet.webp"
  },
  "SSMorph": {
    "name": "SSMorph",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 832
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "morph-cat",
      "morph-fish",
      "morph-eagle",
      "morph-bear"
    ],
    "animations": {
      "morph-cat": {
        "row": 0,
        "frameCount": 9,
        "fps": 18,
        "loop": true
      },
      "morph-fish": {
        "row": 1,
        "frameCount": 9,
        "fps": 18,
        "loop": true
      },
      "morph-eagle": {
        "row": 2,
        "frameCount": 9,
        "fps": 18,
        "loop": true
      },
      "morph-bear": {
        "row": 3,
        "frameCount": 9,
        "fps": 18,
        "loop": true
      }
    },
    "spritesheet": "SSMorph/output/spritesheet.webp"
  }
};
