// Auto-generated by assemble.ts — do not edit manually
window.CHAR_REGISTRY = {
  "Farmer": {
    "name": "Farmer",
    "type": "char-sprite-v1",
    "dimensions": {
      "width": 1728,
      "height": 1040
    },
    "frameSize": {
      "width": 192,
      "height": 208
    },
    "rows": [
      "walk-down",
      "walk-up",
      "walk-left",
      "tool-use",
      "sleeping"
    ],
    "animations": {
      "walk-down": {
        "row": 0,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-up": {
        "row": 1,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "walk-left": {
        "row": 2,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      },
      "tool-use": {
        "row": 3,
        "frameCount": 9,
        "fps": 8,
        "loop": false
      },
      "sleeping": {
        "row": 4,
        "frameCount": 9,
        "fps": 8,
        "loop": true
      }
    },
    "spritesheet": "Farmer/output/spritesheet.webp"
  }
};
